### ISSUE TITLE
Class 'Goetas\Xsd\XsdToPhp\Jms\Handler\BaseTypesHandler' not found

### ISSUE THREAD

**Issue by sohrobraja3** [AuthorizeNet/sdk-php#102]
I am using the "Quick Usage Example (with Charge Credit Card - Authorize and Capture)" here:
https://github.com/AuthorizeNet/sdk-php

and I am running into this error where I have my code hosted on heroku:

_--PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0 
--local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Goetas\Xsd\XsdToPhp\Jms\Handler\BaseTypesHandler' not found' in /app/vendor/authorizenet/authorizenet/lib/net/authorize/api/controller/base/ApiOperationBase.php:82_ 

When I test transactions on my localhost (using laravel 5.1), I am able to create successful transactions and have not received this error. This only occurs on my live server.

On Postman, I only receive this error: **Class 'Goetas\Xsd\XsdToPhp\Jms\Handler\BaseTypesHandler' not found**

This class and other files do exist in vendors/goetas/...., but I do not understand why this is occuring.

I have not found any instance of anyone dealing with this problem and any help would be greatly appreciated.

Thanks,

**Comment by ashtru** [comment]
For the **$HTTP_RAW_POST_DATA** I suppose you have tried modifying the php.ini to uncomment `;always_populate_raw_post_data = -1` as discussed [here](http://stackoverflow.com/questions/26261001/warning-about-http-raw-post-data-being-deprecated).

I am stil not sure how to replicate the **Goetas\XsdtoPhp** issue.
But if you are using **composer** , it should generate a `vendor` folder instead of `vendors`?

It may be useful, if you provide the logs in _phplog_  file in the root folder, or the folder from where you are executing `php charge-credit-card.php`

Also, since you only wish to run one sample code, you can try cloning [sample-code-php](https://github.com/AuthorizeNet/sample-code-php) instead of sdk-php, run `composer update`, and then `php PaymentTransactions/charge-credit-card.php`

**Comment by sohrobraja3** [comment]
Thank you for responding! I was able to resolve this issue by updating the version from 1.8.4 to 1.8.6.2.

**Comment by LawanyaD** [comment]
What I do??
Fatal error: Class 'vendor\Goetas\Xsd\XsdToPhp\Jms\Handler\BaseTypesHandler' not found

**Comment by AlexLomm** [comment]
Same error here:
Fatal error: Class 'vendor\Goetas\Xsd\XsdToPhp\Jms\Handler\BaseTypesHandler' not found

**Comment by AlexLomm** [comment]
@LawanyaD Have you been able to resolve the problem?

**Comment by LawanyaD** [comment]
Yes, I completed authorize .net payment in my project :)

**Comment by AlexLomm** [comment]
Glad to hear that :). Do you remember what the problem was?

**Comment by LawanyaD** [comment]
I just reconfigure the authorize .net payment library in terminal
