### ISSUE TITLE
Dependencies goetas/xsd2php and goetas/xsd-reader require php 5.4

### ISSUE THREAD

**Issue by gigo6000** [AuthorizeNet/sdk-php#136]
We're currently using php 5.3.10 in our project but now composer is asking to upgrade to 5.4 just because goetas/xsd2php and goetas/xsd-reader require it. 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)              
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for goetas/xsd-reader 2.*@dev -> satisfiable by goetas/xsd-reader[2.0.x-dev].
    - goetas/xsd-reader 2.0.x-dev requires php >=5.4.0 -> your PHP version (5.3.10) does not satisfy that requirement.
  Problem 2
    - goetas/xsd2php 2.0.x-dev requires php >=5.4 -> your PHP version (5.3.10) does not satisfy that requirement.
    - goetas/xsd2php 2.0.0-alpha requires php ~5.4 -> your PHP version (5.3.10) does not satisfy that requirement.
    - Installation request for goetas/xsd2php 2.*@dev -> satisfiable by goetas/xsd2php[2.0.0-alpha, 2.0.x-dev].
```

Current minimum version according to composer is 5.3:
 
```
    "require": {
        "php": "~5.3 || ~7.0",
```

**Comment by brianmc** [comment]
We definitely need to fix that minimum version in our composer file.  The next version of our SDK will probably move to a 5.5 dependency simply because of the security implications of earlier versions now out of support for critical security patches.  http://php.net/supported-versions.php   xsd2php will probably also move to 5.5 dependency because JMSSerializer has moved to 5.5.

Definitely worth considering an upgrade for your system.

**Comment by gigo6000** [comment]
I think people should not be forced to upgrade php, we have an old app that depends on php 5.3 so is not really easy to switch to php 5.4 just because of this library.

**Comment by brianmc** [comment]
You can definitely stay with an older version of our SDK @gigo6000, (e.g. maybe a 1.8.2) so hopefully you are not forced to upgrade, but I do appreciate that's not an ideal solution either.   As I mentioned in the earlier post we have now moved to 5.5 dependency, we simply cannot stay on unsupported versions of PHP due to the security/PCI implications.

One other option may be the community library https://github.com/thephpleague/omnipay-authorizenet but again I understand that involves some rework on your side.

**Comment by gigo6000** [comment]
I think older versions of the SDK are not really usable because of the recent changes in Auth.net. We ended up moving to Braintree (https://github.com/braintree/braintree_php). Thanks for your replies.
