### ISSUE TITLE
Need to make $_xml accessible for logging

### ISSUE THREAD

**Issue by sstringer** [AuthorizeNet/sdk-php#19]
While it is possible to save transactional data to a log file, this gets unwieldy to leave on for any length of time.  Thus, I would like to save the transactional data to my database.

To do this, I need access to the _xml class variable which is protected.  Can someone add a public getter method that retrieves the xml sent and the xml received, respectively?

Thanks,
Steve

**Comment by brianmc** [comment]
Hi @sstringer First apologies for delay in responding to this one, it has been on our reviews as we updated the SDK.  The reluctance we have is that we do not want anyone to inadvertently give themselves a store of sensitive data (e.g. card numbers) simply because they dumped xml requests to file or DB.  We are looking at masked logging and some other options so feel free to respond with any thoughts you have on that.
