### ISSUE TITLE
API return json string include  B(yte) O(rder) M(ark) 0xEF 0xBB 0xBF。

### ISSUE THREAD

**Issue by phpstudyOne** [AuthorizeNet/sdk-php#231]
Hey , guys：
Sorry, I have a question about getCustomerProfileIds  API in '[getCustomerProfileIds](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-profile-ids)' page .
I use the following code：
```php
$this->authorizeUrl = 'https://api.authorize.net/xml/v1/request.api';
$data = '{
    "getCustomerProfileIdsRequest": {
        "merchantAuthentication": {
            "name": "API_LOGIN_ID",
            "transactionKey": "API_TRANSACTION_KEY"
        }
    }
}';
$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, $this->authorizeUrl);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_COOKIESESSION, true);
curl_setopt($curl, CURLOPT_HEADER, 0);
curl_setopt($curl, CURLOPT_POST, 1);
curl_setopt($curl, CURLOPT_POSTFIELDS, urldecode($data));
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 2);
// curl_setopt($curl, CURLOPT_HTTPHEADER,     array('Content-Type: text/plain')); //xml request
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Accept: application/json'));
$result = curl_exec($curl);
```
now I like to decode the json in my application:
`$result = json_decode($result, true);`
**but it returns NULL.**
I had to use the following code to decode.
```php
if (json_decode($result, true)) {
    $result = json_decode($result, true);
} else {
    $result = json_decode(substr($result, 3), true);
}
```

**Comment by AmanaEstates** [comment]
[http://php.net/manual/en/function.json-decode.php](url)

>  NULL is returned if the json cannot be decoded or if the encoded data is deeper than the recursion limit. 

Check the actual response and or headers to make sure the call was fine.

**Comment by phpstudyOne** [comment]
@AmanaEstates , I do not think it is for this reason 。 

 '{"ids":["1810025xxx","1810263xxx","181031xxx".........'
 ^
 |
 This is the UTF-8 BOM

**Comment by AmanaEstates** [comment]
Do an echo on the `$result`. Then run it through a validator, ex: https://jsonlint.com/

Chances are that the string would fail.

**Comment by phpstudyOne** [comment]
@adavidw @AmanaEstates .  I use the `ob_clear()` code ,json_decode still returns NULL, but i use 'json_decode(substr($result, 3), true);' to return normal data. so,I keep my point of view。

**Comment by ashtru** [comment]
Thanks @phpstudyOne for raising this issue and providing with a solution.

**Comment by JoshMoreno** [comment]
This needs to be fixed on authorize.net's end not on the consumer end (this sdk or any other client code).
I'm not sure where to report this to the appropriate authorize.net devs so am posting here. Let me know if there's a more appropriate place to report this.

In my case, I'm writing integration tests and make a post request to this endpoint - https://apitest.authorize.net/xml/v1/request.api. The JSON in the successful response is invalid and causes php's json parser to fail. The issue is there is a BOM right before the actual valid json. Can we please get that removed from the response?

As a workaround
```php
// strips out the BOM
$json = preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $response)
// and now you can parse without an error
$response = json_decode($json, true);
```

This has been an issue since 2014. For reference - 
https://community.developer.authorize.net/t5/Integration-and-Testing/JSON-issues/td-p/48851
