### ISSUE TITLE
addLineItem should limit to 30 entries

### ISSUE THREAD

**Issue by fulldecent** [AuthorizeNet/sdk-php#246]
> The merchant can submit a maximum of 30 distinct line items containing itemized order
information for each transaction. 

Reference: https://www.authorize.net/content/dam/authorize/documents/AIM_guide.pdf version June 2016 page 39. 

However this PHP API allows more than 30 items.

As current, this API allows submitting invalid requests to the authorize gateway server.

**Comment by adavidw** [comment]
I just want to write a warning to anyone watching that the documentation referenced is out of date and shouldn't be used as an authoritative source _unless you are specifically working with our AIM name-value pair API_ (reference pg. 6 in that PDF). Generally, this PHP SDK sends requests using our Authorize.Net XML API, and authoritative documentation for that is at http://developer.authorize.net/api/reference/. However, the SDK also includes (deprecated) support for the older name-value pair API, and that's the file that this pull request patches, so it's still appropriate to reference here.

That said, the current API also limits you to a max 30 line items, and off the top of my head, I don't know if the other parts of the code for the XML API are enforcing that. I'll try to remember to check when I have time.

It's generally better when the SDK can handle bad requests instead of passing them on, so I appreciate the fix. But, considering that this SDK's support for the AIM NVP API is deprecated, I'm not sure if anyone will ever pull this in.

**Comment by fulldecent** [comment]
Thank you for explaining.

I recommend that the above documentation I have referenced should be amended to include a deprecation notice.

**Comment by adavidw** [comment]
There is one on page 6, but it's not big enough for my tastes. If it were up to me, it would be in giant letters taking up the first two pages :)

**Comment by fulldecent** [comment]
Ok, for clarity, does the 30-item limit apply for this PHP SDK? And if so, is this PR in scope to be merged?

**Comment by adavidw** [comment]
Yes, it applies to all usages in this SDK, so the PR is definitely in scope.

**Comment by adavidw** [comment]
Unfortunately, we can't make this change because we have a separate project that will end up substantially raising the limit on line items early next year. Even though that's not happening right now, we'd rather not have versions of the SDK floating around out there that artificially limit that value and thus wouldn't be raised when the limit is raised on the server end.

One more bit of good news: If you follow [the URL to the PDF](https://www.authorize.net/content/dam/authorize/documents/AIM_guide.pdf) that was given in the original post, you'll find a nice obnoxious deprecation notice right up front and center.

**Comment by fulldecent** [comment]
Nice and nice. Thanks for the quick reply. And I am happy to clear out some of the issues/PRs on my list today!

**Comment by greggles** [comment]
> a separate project that will end up substantially raising the limit on line items early next year. 

Did that get delayed? I've just run into this issue when using the Drupal Commerce Auth.net payment gateway integration.

**Comment by rsnyd46** [comment]
Same here @greggles.  Any news on this limit?
