### ISSUE TITLE
Credit Card Expiration Data: consistent documentation

### ISSUE THREAD

**Issue by alexsasharegan** [AuthorizeNet/sdk-php#249]
It would seem that the documentation available at http://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card differs from the usage in the sample code available at https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-credit-card.php#L23.

I'm revisiting some cc processing code we implemented several months ago, and I see that we used the format `MM-YYYY`. Have there been changes in this? What is the correct format?

![screen shot 2017-07-28 at 3 16 44 pm](https://user-images.githubusercontent.com/16269252/28738373-f01ed90e-73a7-11e7-91c7-b14603c64a5b.png)
![screen shot 2017-07-28 at 3 16 57 pm](https://user-images.githubusercontent.com/16269252/28738372-f00cad10-73a7-11e7-8087-da080cca6194.png)

**Comment by adavidw** [comment]
The underlying API will support sending an expiration date in nearly any reasonable combination of month and year and separator. These are all acceptable formats:

- YYYY-MM
- MM-YY
- MM-YYYY
- MMYY
- MMYYYY
- YYYY/MM
- MM/YY
- MM/YYYY
- YYYY,MM
- MM,YY
- MM,YYYY

Listing all possible formats in every possible place that we discuss expiration date is probably not a good idea, though, for a few reasons. One, we don't want to just say "any combination in any order will work" because not all will. Two, listing every possibility is bulky and cumbersome. Three, while this API won't change what it accepts, future products might be more constrained in what they accept, so we don't want people to get in the habit of using MMYY if we offer other products that require YYYY-MM, for example.

So, to answer your question of what the "correct" format is: The "correct" format would be the one that we want to guarantee is supported by future products as well. That's a gYearMonth (YYYY-MM). The documentation should reflect that, although not all sample code has been changed to reflect that. I'll add something internally to track at least going through our sample code repos and doc samples to make consistent there.

**Comment by alexsasharegan** [comment]
Thank you! That's what I was looking for—the most versatile format across all your APIs. Many Thanks!
