### ISSUE TITLE
Latest version to support PHP 5.4.45?

### ISSUE THREAD

**Issue by PCGeekBrain** [AuthorizeNet/sdk-php#256]
What is the latest version of the SDK to support PHP 5.4?

The last readme I could find in the releases branch that still said "PHP 5.3+" would be 1.9.2 from last December. Is this correct?

Thanks :-)

1.9.2 commit: https://github.com/AuthorizeNet/sdk-php/tree/7a7a2145b82bb8c181e18d292512061e908af72a

**Comment by adavidw** [comment]
Hi @PCGeekBrain,

1.9.2 still said "5.3" in the readme, but the composer.json was requiring 5.5 in that release. The last release with 5.3 as the minimum in the composer.json was 1.8.9.

That said, I don't know what's specifically changed between those versions that would preclude compatibility with 5.4. It's possible if you just edit the composer.json that even the latest version might work on 5.4. That doesn't mean it's a good idea, though.

Anything older than 5.6 isn't going to be PCI-DSS compliant because those older versions aren't receiving security fixes (at least not from the PHP Group. If you have Red Hat Enterprise Linux/CentOS, they do backport security fixes, but that's a rare exception).

So, you really shouldn't be using anything older than 5.6 for any payment processing. You are putting your merchant or customers at serious risk if you do.

**Comment by adavidw** [comment]
Handy chart for PHP security fix support here:
http://php.net/supported-versions.php

**Comment by PCGeekBrain** [comment]
Thanks @adavidw I'll try it out.

**Comment by PCGeekBrain** [comment]
Good morning, For anyone else with this issue the latest version that actually works seems to be 1.8.1 due to one of the dependencies added in 1.8.2 or 1.8.3 requiring PHP 5.5
