### ISSUE TITLE
Did not get response data of customerProfilePaymentId after successfully save the customer payment profile

### ISSUE THREAD

**Issue by phpstudyOne** [AuthorizeNet/sdk-php#257]
I Using the Accept Customer Hosted Form save user's CC info, But when I click the save button to successfully save the data and found that the returned data does not include "CustomerProfilePaymentId" .
the response data: 
`{qstr: "action=successfulSave", parent: "https://test.authorize.net/customer/addPayment"}`

![image](https://user-images.githubusercontent.com/11455285/30258855-8e6caf9a-96ef-11e7-9b4d-bae2a5d2826e.png)

![image](https://user-images.githubusercontent.com/11455285/30258871-9e9da360-96ef-11e7-85a2-c1a1c517bfc6.png)

The "addPayment" of the Accept Customer Hosted Form return data can be similar to the payment? Because I need "CustomerPaymentProfileId" for further processing .

![image](https://user-images.githubusercontent.com/11455285/30258916-ef23cbf2-96ef-11e7-80c2-ede340629f8c.png)

```json
"action=transactResponse&response={"accountType":"Visa","accountNumber":"XXXX1111","transId":"60029425597",
"responseCode":"1","authorization":"0Q8PP2",
"billTo":{"phoneNumber":"1231231234","firstName":"Ellen","lastName":"Johnson","company":"Souveniropolis","address":"14 Main Street","city":"Pecan Springs",
"state":"TX","zip":"44628","country":"USA"},"shipTo":{},
"orderDescription":"Product Description","taxAmount":"4.26","shippingAmount":"4.26",
"dutyAmount":"8.55","customerId":"99999456654",
"totalAmount":"0.50","poNumber":"456654","orderInvoiceNumber":"INV-12345","dateTime":"9/11/2017 4:50:41 AM"}"
```

**Comment by adavidw** [comment]
Hi @phpstudyOne,

Unfortunately, it doesn't currently do what you describe, but I can definitely see the usefulness in such a scenario.
 
I'd encourage you to post this onto our [Ideas Forum](https://community.developer.authorize.net/t5/Ideas/idb-p/ideas) where others can take a look, contribute feedback, and vote for new features.

As a workaround, since you already know the profile ID, you can listen for a [Webhooks](http://developer.authorize.net/api/reference/features/webhooks.html) notification that the new profile has been created, or just make a [getCustomerProfile](http://developer.authorize.net/api/reference/#customer-profiles-get-customer-profile) call at the right time to find the new payment profile.
