### ISSUE TITLE
How to change the save button on the right and cancel button on the left on Payment form.

### ISSUE THREAD

**Issue by phpstudyOne** [AuthorizeNet/sdk-php#272]
As a user
I want to see SAVE button on the right
Because I get used to the most popular action item on the right
Given I'm a user
When I'm on the PAYMENT INFO tab
Then I should see the SAVE button on the right and the cancel button on the left

![image](https://user-images.githubusercontent.com/11455285/32588221-352f4776-c548-11e7-8eff-6fce0d4d37dd.png)

                                        ||
                                        ||
                                change  ||   to
                                        ||

![image](https://user-images.githubusercontent.com/11455285/32588283-973fa726-c548-11e7-8a58-88274f8706f0.png)

**Comment by ashtru** [comment]
This looks like a good feature request. But, it is not possible in the current Accept implementation.
Since this is not the proper sdk for Accept, I have asked this [question](https://community.developer.authorize.net/t5/Integration-and-Testing/Accept-Customer-Save-Button-on-the-right-instead-of-left/td-p/60776) in the developer community.

I would also recommend you to [add it as a new idea](https://community.developer.authorize.net/t5/forums/postpage/board-id/ideas) in the Ideas section, so that it can be considered as a feature in future.
