### ISSUE TITLE
Simple code error 500

### ISSUE THREAD

**Issue by captainozee** [AuthorizeNet/sdk-php#277]
I would like someone to help me create custom SPL because I'm using GoDaddy shear host I can't use the composer. If someone can give me the solution to create vendor folder will be great

**Comment by ashtru** [comment]
Hi @captainozee 
Composer is required:

1. For generating the vendor folder. If you do not have composer on the main server, one solution is to use composer on another system to generate the vendor folder, and copy the folder to your main server, so that it is in the root of the sdk-php.
2. Composer is also used as the default autoloader. Since you don't have composer, you can use the [autoload.php](https://github.com/AuthorizeNet/sdk-php/blob/master/autoload.php) already present  in the sdk.
So, you would use `require 'autoload.php'` instead of the` require 'vendor/autoload.php'` as shown in[ sample codes](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-credit-card.php#L2). Note that you still need the vendor folder to be present, using one of the methods in step 1.

**Comment by ashtru** [comment]
@captainozee, 
Did this solution work for you? Please provide your feedback in case you still have questions.

**Comment by ashtru** [comment]
Closing this issues due to inactivity.
