### ISSUE TITLE
How to change the error message 

### ISSUE THREAD

**Issue by rajmohanvy** [AuthorizeNet/sdk-php#319]
Hi team,

I have an issue with error message displays. How to remove the file path from the error message.

My Code : `echo "Response : " . $errorMessages[0]->getCode() . "  " .$errorMessages[0]->getText() . "\n";`

Output
Response : The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:name' element is invalid - The value 'The sample subscrition for donation process.' is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value.

Output need:
Response: The actual length is greater than the MaxLength value.

**Comment by ashtru** [comment]
The error received from the API is a XSD validation error, which happens if some field violates the API contract defined for Authorize.Net APIs. You can modify your code (Sample Code) as below to get the required message:

```
        echo "ERROR :  Invalid response\n";
        $errorMessages = $response->getMessages()->getMessage();
        $debug=$errorMessages[0]->getText();
        if(strpos($debug,'AnetApi/xml/v1/schema/AnetApiSchema.xsd:name' )==true)
        {
              $arrErrMsg=explode("-",$debug);
            if(strpos($arrErrMsg[2],'The actual length is greater than the MaxLength value')==true)
            {
                echo "Response : " . $errorMessages[0]->getCode() . "  " .$arrErrMsg[2]. "\n";
                return;
            }
            echo "Response : " . $errorMessages[0]->getCode() . "  " .$errorMessages[0]->getText() . "\n";
        }
```
Need to replace the above code instead of existing:
```
        echo "ERROR :  Invalid response\n";
        $errorMessages = $response->getMessages()->getMessage();
        echo "Response : " . $errorMessages[0]->getCode() . "  " .$errorMessages[0]->getText() . "\n";
```


And also, we would recommend you to add frontend validation in your webpage/application before calling the Authorize.Net API.
If you see the Request tab in the API documentation for create subscription , the max length for the name of a subscription is 50. You can add the validation for your input for subscription name, that it cannot exceed 50 characters.

**Comment by chsriniv9** [comment]
Based on the inputs and solution provided by @ashtru closing this issue. Feel free to re-open in case further assistance required.

**Comment by techkomal** [comment]
How can i change the error message response from AVS in authorize.net???
