### ISSUE TITLE
about company field on the Accept Customer Hosted Form

### ISSUE THREAD

**Issue by phpstudyone** [AuthorizeNet/sdk-php#335]
Recently I tested the payment process on my website on QA environment(sandbox), I found there is a new field called company on the Accept Customer Hosted Form 

![image](https://user-images.githubusercontent.com/11455285/45747078-6051d900-bc37-11e8-9d1c-d6eb83c69525.png)

but there isn’t on the prod environment

![image](https://user-images.githubusercontent.com/11455285/45747358-3220c900-bc38-11e8-8d72-aa9800dfb2ff.png)

Could you please tell me when will you launch it to live environment so that my team can make an adjustment timely to minimize the impact to our users? Whether the company can be set not to be displayed on the Accept Customer Hosted Form?

**Comment by phpstudyone** [comment]
The PROD environment also has a company field today. Can you tell me what happened?

**Comment by gnongsie** [comment]
Hi @phpstudyone ,

Thanks for bringing this to our attention. I believe this was due to an update in the forms and you were testing during one of our maintenance periods.

I would like to assist in any other way possible. So I'll keep this issue open for you if you have any other queries. Otherwise, I don't see this as a valid issue anymore.
