### ISSUE TITLE
new goetas-webservices/xsd2php-runtime will allow jms/serializer v2.0

### ISSUE THREAD

**Issue by goetas** [AuthorizeNet/sdk-php#345]
as of https://github.com/goetas-webservices/xsd2php-runtime/pull/8 currently only in `master`, when released, users with php 7.2 will get jms/serializer 2.0 instead of 1.x.

The plan is to release it in 5-7 days (or later in case you will find bugs).

jms/serializer 2.0 should be fully backward compatible, but since `AuthorizeNet/sdk-php` is a pretty mission critical project (payments involved...) I'm warning you some days in advance to avoid users getting payments not working anymore in case of updates...

Can you please test your project using `goetas-webservices/xsd2php-runtime:master-dev` on php 7.2?

Hopefully no changes should be required on your side.

**Comment by gnongsie** [comment]
Hi @goetas ,

I'll raise this with the relevant team. Thank you for the heads up.

We'll perform the necessary testing and let you know.

**Comment by ashtru** [comment]
We have verified that the **SDK works** fine using `goetas-webservices/xsd2php-runtime:master-dev` , with jms/serializer 2.0, on php 7.2 .

The code in _[nodependency-rc](https://github.com/AuthorizeNet/sdk-php/tree/nodependency-rc)_ will be unaffected due to this change.

Thanks for your personal attention, Ashmir  👍 👍

**Comment by goetas** [comment]
Great news
