### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by SteveDesmond-ca** [AuthorizeNet/sdk-php#383]
As of right now, ANet's PHP SDK cannot run on PHP 7.4, as it throws errors about invalid code in the various model types, e.g.
```html
    <h4>A PHP Error was encountered</h4>

    <p>Severity: 8192</p>
    <p>Message: Cannot use "parent" when current class scope has no parent</p>
    <p>Filename: v1/MessagesType.php</p>
    <p>Line Number: 134</p>
```

I believe this is due to the new JIT compiler seeing things like
```php
    return array_merge(parent::jsonSerialize(), $values);
```
on classes that don't actually have `parent`s.

PR #382 already exists and appears to fix this, but even just some news that an in-house solution is in the works would be helpful.

**Comment by Nix-id** [comment]
I also have same problem.

```
Deprecated: Cannot use "parent" when current class scope has no parent in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/OrderType.php on line 532

Deprecated: Cannot use "parent" when current class scope has no parent in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/NameAndAddressType.php on line 262

Deprecated: Cannot use "parent" when current class scope has no parent in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/CustomerDataType.php on line 181

Deprecated: Cannot use "parent" when current class scope has no parent in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/TransactionRequestType.php on line 1122

Deprecated: Cannot use "parent" when current class scope has no parent in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/ANetApiRequestType.php on line 129

Deprecated: Cannot use "parent" when current class scope has no parent in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/ANetApiResponseType.php on line 127

Deprecated: Cannot use "parent" when current class scope has no parent in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType.php on line 889

Deprecated: Cannot use "parent" when current class scope has no parent in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/MessagesType.php on line 134

Deprecated: Cannot use "parent" when current class scope has no parent in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/MessagesType/MessageAType.php on line 97
```

**Comment by witchblade32** [comment]
Also having the same issue with 7.4 and Deprecated: Cannot use "parent" when current class scope has no parent

**Comment by mihaijoldis** [comment]
Same issue on PHP 7.4.10
Cannot use "parent" when current class scope has no parent

**Comment by aetikon** [comment]
Also having this exact same issue on PHP 7.4.

**Comment by jeffussing** [comment]
Same thing here.

**Comment by FactoryAidan** [comment]
✅ I've been able to modify my clone of the codebase to work with `PHP ^7.4` . It has been working well.

I know it's ultimately Authorize.net's responsibility to fix this but it's been 🦗💤  from them and I've been reaching out to them for a long time. I don't know when they're going to accept accountability for this, step up to the plate, and fix it.

⚠️ The issue is that all files in the `lib/net/authorize/api/contract/v1` directory are autogenerated by their cross-platform compiler "based on the XML schema" of Authorize.net's API. This means a human didn't actually spend time making sure the bugged classes made logical sense in the PHP language.

🙇 Unfortunately, without possibly getting sued, I'm not allowed to distribute that code to all of you due to the [license agreement](https://github.com/AuthorizeNet/sdk-php/blob/master/LICENSE.txt) of their codebase unless Authorize.net gives me permission to do so, which they have not yet. But hopefully this feedback will give you all 'some' control of your own success if Authorize.net isn't able to reconsider the decision to rely on a cross-platform compiler before PHP 7.3 reaches [end of support on 6 Dec 2021](https://www.php.net/supported-versions.php).

📖 But as a humble offering, this explains the manual effort to fix all files in the `lib/net/authorize/api/contract/v1` directory to work with `PHP ^7.4`:
- Any class that **`extends` another class** and does **not define its own method `jsonSerialize()`**, I added that method with the same content as its parent. (_Because it definitely has a parent. However, copy the method from the parent right now because we're about to change the parent's method definition in the next step_)
- Any class that does **not `extend` another class** can never have a parent. So I removed the last `if(){}` block in `jsonSerialize()` that checks for a parent class and simply `return $values;` always.

FYI (no changes to):
- Any class that **`extends` another class** and also **defines its own method `jsonSerialize()`**, I left as is; no changes. (Because it definitely has a parent).

ℹ️ I experimented with doing this an 'easier' way that involves less manual file editing and instead inheritance of a wiser `jsonSerialize()` method in the base classes. Ultimately things didn't behave properly in my experiment and I went down a rabbit's-hole that ultimately didn't pan-out. So I bit the bullet and just stuck to the original plan of updating all the files.

**Comment by rekliner** [comment]
Just want to link to [issue 397](https://github.com/AuthorizeNet/sdk-php/issues/397) from here since it is discussing the same problem and has similar fixes with private repos.  Nobody from authorize.net is coming to the rescue.  This repo appears abandoned.

**Comment by Parker-Bergen** [comment]
After asking some questions I asked about PHP 8 support, it is planned. Just an update since I know some people were looking from some answers. Elisha was also very nice and helpful, small shoutout.
Transcript with Elisha from Authorized.net today:

18:24:18 UTC Parker Bergen : Will support be made for PHP8 in the Authorized.net PHP SDK.
18:24:53 UTC Elisha : There are plans but there is no ETA yet on this. As of now we support up to PHP 7.3 with our SDK.
18:26:00 UTC Parker Bergen : Ok. We would like to keep using Authorized.net but it is stating to get out of our support range, just wanted to make sure it will continue to be supported, and hopefully soon.
18:27:35 UTC Elisha : I understand, that was the latest update from our escalation team as of 1/19/2021. 
18:27:48 UTC Elisha : You can check back with us on a later date if you would like. Was that all I could answer for you today on my end?

**Comment by SteveDesmond-ca** [comment]
Per #407, v2.0.2 supports PHP 7.4+
