### ISSUE TITLE
Issue with CIM - getValidationResponse()

### ISSUE THREAD

**Issue by S1owbro** [AuthorizeNet/sdk-php#44]
*This is a problem I've encountered with the version 1.8.3.1 SDK using the Authorize.net sandbox server. I'm currently unable to test it on the live server.*

This function in the `AuthorizeNetCIM_Response` class,
```php
public function getValidationResponse()
{
  return new AuthorizeNetAIM_Response($this->_getElementContents("validationDirectResponse"), ",", "|", array());
}
```
is passing the `AuthorizeNetAIM_Response` constructor an `$encap_char` value of "|". However, the Authorize.net server isn't using an encapsulating character, so the `AuthorizeNetAIM_Response` fields fail to populate. Reverting the  `$encap_char` value back to "", like it was in version 1.1.8, fixes the problem.

The related `AuthorizeNetCIM_Response::getValidationResponses()` function is still using a value of "" for `$encap_char`.

**Comment by brianmc** [comment]
Thanks @S1owbro you are correct and we should not be passing that in.

Also one important thing here is that we are going to be deprecating the API method underneath this call  in favor of using the standard createTransaction method which will provide a standardization in processing and removal of that DirectResponse processing.  http://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile

Brian

**Comment by IslandUsurper** [comment]
So, until then, I'm going to have to filter out any commas in the profile addresses?

**Comment by w0rd-driven** [comment]
I'm running into this same problem, was going to make a PR, but I see the PR failed to be merged.

Because `createCustomerPaymentProfile` doesn't have the encapsulation character, `getValidationResponse()` fails to return a parsed `AuthorizeNetAIM_Response`.

That extra options concat in `createCustomerProfileTransaction` requires things like $extraOptions = "x_test_request=TRUE**&**" (note the required ampersand at the end) because the operation being done blindly assumes no extra options would ever be used.

I've worked around all of these issues, I just wish I didn't have to. Pointing composer to a fork that fixes these issues isn't a long term solution to me so it would be great if the PR could be merged in. I see no legitimate reason why it hasn't been included so far either as the Travis-CI failure doesn't even seem relevant.

**Comment by brianmc** [comment]
Hi guys,  the new model (along with the new profile support in CreateTransaction) should mean that you don't need to point to a future fork of ours or compromise with workarounds of your own.

We have our new sample code repos for PHP almost finished you can check out the samples for creating and charging profiles here, they work with the current released version of the SDK 1.8.5

https://github.com/AuthorizeNet/sample-code-php/tree/master/CustomerProfiles
https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php

**Comment by brianmc** [comment]
Haven't heard back on this one but we are actually planning to even retrofit the old CIM call to use CreateTransaction rather than the CreateCustomerProfileTransaction so this issue should disappear even in old model soon.  Feel free to shout if neither of these solutions works for you.

Thanks,  Brian

**Comment by w0rd-driven** [comment]
I can't change to the new model yet, sadly, and this is still biting.

My problem isn't with `createCustomerProfileTransaction` as that is still encapsulated and subsequently the `getTransactionResponse()` call still works. The issue I have is when I use `createCustomerPaymentProfileRequest`, `getValidationResponse()` returns a broken AIM response because it is **not encapsulated**.

I feel like this one small correction fixes what should pass as a bug. I see no instance where this method would actually return a functional AuthorizeNetAIM_Response object.
