### ISSUE TITLE
Possible missing certificate

### ISSUE THREAD

**Issue by katagawa-u16** [AuthorizeNet/sdk-php#49]
The article [Production Certificate Upgrades begin May 27 2015](http://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Production-Certificate-Upgrades-begin-May-27-2015/bc-p/50616) states that the certificate "Baltimore CyberTrust Root" is required, but the currently shipping version of the SDK (1.8.3.3 as of this writing) doesn't appear to include it in cert.pem https://github.com/AuthorizeNet/sdk-php/blob/1.8.3.3/lib/ssl/cert.pem

Shouldn't that certificate be there?

**Comment by brianmc** [comment]
Hi @katagawa-u16, 

You're correct that the CyberTrust cert is not in the current file, that's because we're not currently using that cert.  Because we wanted to minimize updates to that file we wanted to be absolutely sure of the cert before we update. 

You might see the wording in the article says "We will potentially utilize certificates from three vendors: Entrust, GeoTrust, and CyberTrust."  So the CyberTrust cert may be used but we only wanted to update the pem file when we knew for sure.

Thanks again for the heads up,
Brian
