### ISSUE TITLE
How to search/get a profile based on merchantCustomerID instead profileID

### ISSUE THREAD

**Issue by timh5** [AuthorizeNet/sdk-php#59]
As I understand it, the customerProfileID is something Auth.Net assigns.
But merchantCustomerID is something I assign at creation.

that means if I can only get a customer profile using profileID, I need to store that profileID on my side...

But... HOW can I fetch a profile based on merchantCustomerID instead so that I dont need to do that?

**Comment by TrevorW** [comment]
We do not currently have an option to search for CIM profiles through our API. The only option that I can offer would be to retrieve a list of customerProfiles and to iterate through them in order to find the profile in question.  

It is recommended to always store the profile ID generated by Authorize.Net when a profile is created, but you aren't the first person to ask for some form of API based search and it is something that we are investigating for a future enhancement.

**Comment by brianmc** [comment]
Hi @timh5 ,  I'm the product owner for our API and I have added this as a feature request in our backlog.  We will be enhancing our search/reporting capabilities via the API and this is a great example of that need.  Thanks again for the feedback, please feel free to open an Idea request on our Ideas forum at http://community.developer.authorize.net/t5/Ideas/idb-p/ideas  That way you'll get active tracking on the feature request and hopefully community upvoting.

**Comment by bherrmann7** [comment]
You can effect a search by attempting to create a profile with a given merchantCustomerID and have it fail.  when it fails, it tells you in the error message the provfileId.

Kind of a hack
